global:
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'kpranesh2004@gmail.com'
  smtp_auth_username: 'kpranesh2004@gmail.com'
  smtp_auth_password: 'fgit bsjw mbcw nvlu'
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'email-alert'

receivers:
  - name: 'email-alert'
    email_configs:
      - to: 'praneshk.22it@kongu.edu'
        send_resolved: true
        headers:
          subject: 'Test Alert Notification'

templates:
  - '/etc/alertmanager/template/*.tmpl'
